name: build

on:
  push:
    tags: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build plugin
      run: |
        curl -sLo .php https://raw.githubusercontent.com/pmmp/DevTools/master/src/ConsoleScript.php
        php -dphar.readonly=0 .php --make ./ --out ${{ github.event.repository.name }}_v${{ github.ref_name }}.phar

    - uses: softprops/action-gh-release@v0.1.14
      with:
        files: ${{ github.event.repository.name }}_v${{ github.ref_name }}.phar
