name: Create Release Build

on:
  push:
    tags:
      - '*'

env:
  OUTPUT_FILE: ${{ github.event.repository.name }}_v${{ github.ref_name }}.phar

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Change plugin structure from PSR-4 to PSR-0
      run: php -r '$a=yaml_parse_file($b="plugin.yml");$c=str_replace("\\","/",$a[$d="src-namespace-prefix"]??exit);
        system("mkdir -p _/$c;mv src/* _/$c;rmdir src;mv _ src");
        unset($a[$d]);yaml_emit_file($b,$a);'

    - name: Build plugin
      run: curl -sL https://raw.githubusercontent.com/pmmp/DevTools/1.17.0/src/ConsoleScript.php | php -dphar.readonly=0 -- --make ./ --out $OUTPUT_FILE

    - name: Infect virions
      run: php -r '
        $data = yaml_parse_file(".poggit.yml") ?:["projects" => [[]]];
        foreach(reset($data["projects"])["libs"] ?? [] as $lib){
          file_put_contents("virion.phar", file_get_contents("https://poggit.pmmp.io/v.dl/{$lib["src"]}/" . ($lib["version"] ?? "*")));
          system("php -dphar.readonly=0 virion.phar ${{ env.OUTPUT_FILE }}");
        }'

    - uses: softprops/action-gh-release@v0.1.15
      with:
        name: ${{ github.event.repository.name }} ${{ github.ref_name }}
        generate_release_notes: true
        files: ${{ env.OUTPUT_FILE }}
